name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    env:
      solutionpath: .\WinNetCoreApp\
      
    runs-on: ['self-hosted','Windows']

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore ${{ env.solutionpath }}
    - name: Build
      run: dotnet build ${{ env.solutionpath }} --no-restore
    - name: Test
      run: dotnet test ${{ env.solutionpath }} --no-build --verbosity normal

  deploy:
   runs-on: ubuntu-latest
   needs: build
   steps:
   - name: test
     run: 'echo test'
   - name: Chuck Norris quote
      # You may pin to the exact commit or the version.
      # uses: glav/chuck-norris-quote@ab2f5ed65aa44b84d8a63ac593e838f3d7472836
     uses: glav/chuck-norris-quote@v1.0
